### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by yang968** [yang968/Trickstr#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by ryan-mapa** [comment]
Looking good so far! here are some items to check off before auth is complete:
- [x] Finish styling your "navbar" for the logout button and welcome message

Styling looks awesome!
